### ISSUE TITLE
conflict if MAXBUFFERSIZE is larger than 127

### ISSUE THREAD

**Issue by jwende** [adafruit/Adafruit_MQTT_Library#103]
https://github.com/adafruit/Adafruit_MQTT_Library/blob/974f4b8713a83d01b040a0d23b798d3f2978d990/Adafruit_MQTT.cpp#L464

in the case of a larger message (larger than 127 bytes) the remaining packet lenght will take buffer[1] and [2] ... or even [3] so the code needs to take this into account ....

cheers
Joerg

**Comment by maseth** [comment]
See #185 and #183, same problem.

**Comment by xdylanm** [comment]
this should be resolved with PR #193
