### ISSUE TITLE
MOVED: getting compiler error with CC3000 & Arduino Uno & MQTT Library, can't get connected to Adafruit IO site

### ISSUE THREAD

**Issue by jwcooper** [adafruit/Adafruit_MQTT_Library#11]
@mtneco48

Have used cc3000 before many times, and have reviewed CC3000 shield startup again today. All of my example CC3000 programs work with the CC3000 wifi and make connections to sites functioning properly, but when I try to run the Adafruit IO Basics: Digital Outputs to get familiarized with the new system and software, I am running into a problem with a compiler error using the prescribed Adafruit IO Basic Sketches/Adafruit CC3000/digital_output.ino and the loading the 3 required libraries(CC3000, MQTT and SleepyDog) .

Arduino: 1.0.6 (Windows 7), Board: "Arduino Uno"
COMPILER ERROR CODE RECEIVED:

digital_out.cpp.o: In function connect()': C:\Program Files (x86)\Arduino/digital_out.ino:162: undefined reference toCC3000connect(char const, char const, unsigned char)'
digital_out.cpp.o: In function setup': C:\Program Files (x86)\Arduino/digital_out.ino:95: undefined reference toCC3000connect(char const, char const, unsigned char)'

When I run the example, mqtt_cc3k.ino, in the MQTT Library , the cc3000 says that it makes a connection to the router, but can not get a DHCP and keeps resetting.

OUTPUT Dialog:

Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

What is the correct CC3000 firmware version and driverpatch version are working with the cc3000 to make the connection to Adafruit IO? I have reloaded my CC3000 Library and it still does not work? I went back to the older version of the Arduino IDE 1.0.6 and that doesn't help???
ANY THING ELSE I SHOULD BE TRYING??

**Comment by toddtreece** [comment]
@mtneco48 Make sure you have `v0.11.1` of the Adafruit MQTT Library, and `v1.0.3` of the CC3000 Library installed using the Arduino 1.6.4+ Library Manager. It looks to me like you are using an old version of one of them. Let me know if that's not the issue.

**Comment by toddtreece** [comment]
the user opened a new issue (adafruit/io-issues#51), so i'm closing this duplicate.
