### ISSUE TITLE
I have this problem: No such file or directory when compile

### ISSUE THREAD

**Issue by thesofial** [adafruit/Adafruit_MQTT_Library#134]
Hello, please help me, I got this problem when I compile the code.
![2018-10-19_220407](https://user-images.githubusercontent.com/39992428/47226618-3aad2080-d3eb-11e8-8c3d-6e3a729f662f.png)
What should I do now? Thank for your attention.

**Comment by abachman** [comment]
Arduino is looking for the [Adafruit FONA library](https://github.com/adafruit/Adafruit_FONA), which is a different project from this one.

**Comment by thesofial** [comment]
> Arduino is looking for the [Adafruit FONA library](https://github.com/adafruit/Adafruit_FONA), which is a different project from this one.

Thank you, I fixed it.
