### ISSUE TITLE
Examples are incorrect

### ISSUE THREAD

**Issue by Fredfishface** [adafruit/Adafruit_MQTT_Library#142]
The example file contain an error:

In verify Fingerpint

if (!client.connect(host, AIO_SERVERPORT)) {
    Serial.println("Connection failed. Halting execution.");
    while(1);
  }

fails if you don't first set the client fingerprint using:

 Serial.printf("Using fingerprint '%s'\n", fingerprint);
 client.setFingerprint(fingerprint);

**Comment by ladyada** [comment]
which example?

**Comment by aandroide** [comment]
@ladyada  adafruitio_secure_esp8266 it is the only example that uses fingerprints

**Comment by ladyada** [comment]
ok thanks
@brentru take a look!

**Comment by aandroide** [comment]
in addition, the key must be changed:
const char* fingerprint = "AD 4B 64 B3 67 40 B5 FC 0E 51 9B BD 25 E9 7F 88 B6 2A A3 5B";
to:
const char* fingerprint = "77 00 54 2D DA E7 D8 03 27 31 23 99 EB 27 DB CB A5 4C 57 18";

**Comment by brentru** [comment]
@aandroide Thanks for the issue. I'll put in a PR to change the `fingerprint` for Adafruit IO - it does need to be updated. 

After changing the `fingerprint` value, I was not able to replicate the failure you mentioned when running the `adafruitio_secure_esp8266` sketch without setting the fingerprint first. 

Can you paste the code you're running and the output from the serial monitor?

**Comment by brentru** [comment]
Fixed in `master`, closing...
