### ISSUE TITLE
Dynamic group names

### ISSUE THREAD

**Issue by Daemach** [adafruit/Adafruit_MQTT_Library#16]
I'm trying to use the MQTT library with the adafruit IO service, though it could be used anywhere.  I need to group my feeds by device, and, therefore, I need unique group names to keep all of the feeds separate.  I do this by pulling a serial number from a flash chip and appending it to a common group name.  The problem is that PROGMEM doesn't like variables and your library forces me to store the group name in PROGMEM.  How can I create a group name made up of a constant and a variable so I don't have to manually insert a serial number and upload separate code to 100000 devices?

Please see this thread for more information: https://forums.adafruit.com/viewtopic.php?f=56&t=83145&p=420493

**Comment by jwcooper** [comment]
Closing this, as you can actually set the topics dynamically. The examples use PROGMEM to save memory.

See here: https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/Adafruit_MQTT.cpp#L597
