### ISSUE TITLE
Packet Length Issues

### ISSUE THREAD

**Issue by toddtreece** [adafruit/Adafruit_MQTT_Library#17]
there seem to be a couple issues with the publish packet length. currently the payload seems to be limited to 128 chars. i think the problem is related to length being stored as uint16_t, and sent as a uint8_t: https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/Adafruit_MQTT.cpp#L517

also, maybe we could make publish return error codes, and generalize the [error code printer](https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/Adafruit_MQTT.cpp#L207)? that way we could notify the user of the buffer length limit?

**Comment by fsommer1968** [comment]
I agree!  I too have a problem with the very short packet length of 128 character. Any plans for changing that? Bluemix e.g., does not work very well with such small payloads.

**Comment by johnpica** [comment]
I cannot receive messages greater than 128 chars.
I increased the SUBSCRIPTIONDATALEN=1024 and MAXBUFFERSIZE. but it is not working.
There are some constants used in Adafruit_MQTT::readFullPacket
0x80 (128)

**Comment by moxiea** [comment]
`
uint8_t encodePayloadLength(uint8_t *p,uint16_t length)
{
  uint8_t digit,offset=1;
  do {
        digit = length % 128;
        length = length / 128;
		// if there are more data to encode, set the top bit of this byte
		if(length>0)
			digit |= 0x80;
		p[offset++] = digit;
  	}  while(length>0); 
  return offset;
}

// as per http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718040
uint16_t Adafruit_MQTT::publishPacket(uint8_t *packet, const char *topic,
                                     uint8_t *data, uint16_t bLen, uint8_t qos) {
  uint8_t *p = packet;
  uint16_t len;
  //////packet header
  p[0] = MQTT_CTRL_PUBLISH << 4 | qos << 1;
  
  uint16_t payload_len= (strlen_P(topic) + strlen(data))+2;//why +2?
  uint8_t offset = encodePayloadLength(p,payload_len); 
  
  p+=offset;	

  // topic comes before packet identifier
  p = stringprint_P(p, topic);

  // add packet identifier. used for checking PUBACK in QOS > 0
  if(qos > 0) {
    p[0] = (packet_id_counter >> 8) & 0xFF;
    p[1] = packet_id_counter & 0xFF;
    p+=2;

    // increment the packet id
    packet_id_counter++;
  }

  memmove(p, data, bLen);
  p+= bLen;
  len = p - packet;
  //packet[1] = len-2; // don't include the 2 bytes of fixed header data
  DEBUG_PRINTLN(F("MQTT publish packet:"));
  DEBUG_PRINTBUFFER(buffer, len);
  return len;
}
`
i modified some code , now i can send messages greater than 128 chars.
ps.some related code alse need modify..

**Comment by ladyada** [comment]
fixed the packet receive/subscription code, tested with 300 byte packet!

**Comment by ladyada** [comment]
also fixed the packet sending code, tested with 300 byte packet

please manually download the library since its not updated in the library manager. try it out! :)

reopen if its still broken.

**Comment by johnpica** [comment]
still cannot receive package larger than 700 byte

**Comment by ladyada** [comment]
@johnpica are you using this with adafruit.io?

**Comment by johnpica** [comment]
@ladyada No

**Comment by ladyada** [comment]
@johnpica OK well, please spend some time with the library code and see if you can trace exactly where the failure is - its not something we can reproduce and right now we're only supporting adafruit.io

**Comment by johnpica** [comment]
@ladyada Hi, sure will do..
can you confirm that on adafruit.io you can subscribe to a topic and receive

60,1730,294,866,50,44,52,140,52,44,56,38,58,38,56,38,56,40,56,40,56,38,56,136,56,38,58,40,54,138,54,138,54,40,54,138,50,142,52,140,58,134,56,136,56,38,58,38,56,38,58,38,56,38,58,40,54,42,48,46,50,46,48,46,50,46,48,48,50,44,52,44,50,44,52,44,52,42,52,44,52,42,52,44,50,46,50,44,52,46,48,46,50,46,50,44,50,46,48,48,48,46,50,46,50,44,52,44,50,44,52,44,52,140,50,140,58,282,290,866,58,136,54,40,52,46,48,46,50,46,48,46,54,42,50,44,52,44,50,142,50,44,52,44,52,140,50,44,52,140,52,140,52,140,50,142,50,144,54,138,54,40,54,42,50,44,52,44,52,42,52,44,52,42,52,44,52,42,52,44,52,44,52,44,50,46,48,46,50,46,52,44,50,44,50,46,54,40,54,42,54,42,52,42,54,42,54,40,54,42,54,40,54,42,54,40,56,40,54,44,50,44,52,44,50,44,52,44,52,42,50,46,54,282,296,864,54,138,54,40,56,40,54,40,56,40,54,40,54,42,54,40,56,40,54,140,52,44,52,42,52,44,52,140,52,140,52,138,54,42,54,138,54,138,54,136,54,42,54,140,52,44,50,140,52,140,52,44,54,40,54,42,54,138,54,138,54,136,56,40,54,40,56,40,54,42,54,40,56,42,52,140,52,140,52,140,52,140,54,136,54,42,54,138,54,40,54,42,54,138,54,40,54,42,54,44,52,42,52,44,52,42,52,44,52,140,54,136,56,0

**Comment by ladyada** [comment]
hiya you will have to do any testing necessary on your own
