### ISSUE TITLE
ssl connect failed

### ISSUE THREAD

**Issue by myie9** [adafruit/Adafruit_MQTT_Library#175]
ssl connect failed for connecting to : baidu Iot.

(https://cloud.baidu.com/product/iot.html)
 gfshili01.mqtt.iot.bj.baidubce.com
 use 1884 for SSL;  tcp: 1883
but tcp is ok.

lib is used in PIO of VSCode.

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

**Comment by brentru** [comment]
Please contact Baidu IoT for assistance with their IoT platform.
