### ISSUE TITLE
Esp8266 does not connect to Mqtt from wifi data network shared by smartphone

### ISSUE THREAD

**Issue by Alejous** [adafruit/Adafruit_MQTT_Library#176]
Hello everyone.
I am using an esp8266 board and it works wonderfully, I can publish and subscribe to all topics without problem while I have the connection to the wifi (router) of my house, but when I want to connect the esp8266 to the wifi that my smartphone shares if I can connect and it assigns the ip to esp8266 but it does not connect to MQTT sometimes it says that it is not authorized and most of the time it says that the connection has failed.
![error_mqtt](https://user-images.githubusercontent.com/39806228/84001632-a62f6300-a92c-11ea-978e-713e3e03258c.jpg)

**Comment by jonorozcoc** [comment]
You can't use your phone WiFi Hotspot to connect to your mqtt broker as it doesn't stay on the same network. If you want to use it in that way you can use WiFi direct or make your broker available to internet
