### ISSUE TITLE
Multiple ESP8266 - Adafruit Huzzah

### ISSUE THREAD

**Issue by bphick** [adafruit/Adafruit_MQTT_Library#19]
Both of my feeds on two different PCs were down each of the last two Fridays. Checking in on Saturdays in the PMs, both times they had not recovered. The guages show a read that hasn't moved since I saw them Friday, and the charts say "no data." I reset one of my devices to see if it made any difference... And yes it did, but looking in the IDE (I got tired of trying to compile under IDE 1.6.6 with no luck)

The IDE Serial monitor read: 
"Failed to publish temperature.
Failed to publish humidity"

I am running just the stock standard Huzzah ESP8266 connected to a DHT22... all vanilla and hooked, from the project posting on the main Adafruit website for the Huzzah.  They are connected to PC for power. All seems to check out from my end.

What I learned is that when one started working, it kicked the other off Adafruit.io.  So only one works at a time. They were fine for nearly 2 months before the last 2 weekends without a glitch.   
I am operating with the load from IDE 1.6.5 which compiles fines without a glitch (unlike 1.6.6).  ... All was fine but all of the sudden, the last two weeks have been really flakey.  

Jwcooper suggested the upgrade to the new MQTT code, but that won't compile in IDE 1.6.5, and it's a lot to go through to put 1.6.6 if I am going to have the same problems (won't compile) as I had when I last had it installed over the weekend.

Thoughts???  BTW: We were working on this on another Adafruit.IO thread called "Is Adafruit.io Down?... you can get caught up here...  https://forums.adafruit.com/viewtopic.php?f=56&t=83943

**Comment by ladyada** [comment]
hiya, tech support is only handled in the forums, please continue to post there :)

IDE 1.6.6 has bugs that make it not support ESP8266 very well, stick to 1.6.5!
