### ISSUE TITLE
How to use to set callback to a class member function ?

### ISSUE THREAD

**Issue by tavdog** [adafruit/Adafruit_MQTT_Library#198]
Is there a way to use the library inside of a class and then set a callback to be one of the class functions ?
I can't figure out a way to do this ? It seems to work without a problem with the PubSubClient but I'd rather use this library because it it more robust when it comes to reconnecting.
I'm using esp8266 with Arduino. 
<img width="1022" alt="Screen Shot 2021-07-11 at 11 Sun 11 55 58 PM" src="https://user-images.githubusercontent.com/8324295/125272802-f69f8f80-e2a7-11eb-86cc-2c36917f4284.png">

**Comment by brentru** [comment]
> Is there a way to use the library inside of a class and then set a callback to be one of the class functions ?

Nope, you'd need to make `data_callback` and `command_callback` globally scoped functions or `static`
