### ISSUE TITLE
Feature Request: Add functionality for the Arduino Protenta Pro Series of boards

### ISSUE THREAD

**Issue by hpssjellis** [adafruit/Adafruit_MQTT_Library#212]
**Feature Request: Add functionality for the Arduino Protenta Pro Series of boards**

@ladyada 

I specifically use the PortentaH7 which as far as I can tell does not work using any of the Adafruit_MQTT_Library  listed examples. So far the problem seems to be that the Portenta [WiFiSSLClient](https://github.com/arduino/ArduinoCore-mbed/tree/master/libraries/WiFi/src) type does not support the Adafruit ```client.setFingerprint(fingerprint);```

I realize Adafruit does not sell any of the Arduino Pro series. Hopefully they will in the future as I am making an entire [Maker100](https://github.com/hpssjellis/maker100) course based on them. I already have really good Adafruit through Helium  connectivity using the Lora Vision Shield, and have great webpage [connectivity](https://hpssjellis.github.io/my-examples-of-iot-platforms/public/index.html) to the Adafruit cloud. I just need the Arduino PortentaH7  to connect using both HTTP and MQTT.

I will continue to test. Does anyone have any suggestions?

**Comment by ladyada** [comment]
hiya, we don't own that board so if you'd like to add support please submit a PR!

**Comment by hpssjellis** [comment]
I will try my best to submit the PR @ladyada. Might take a while to get it working.

Closing this now.
