### ISSUE TITLE
No been able to publish into adafruit IO using ESP8266

### ISSUE THREAD

**Issue by andrealmeidadomingues** [adafruit/Adafruit_MQTT_Library#23]
Hello,

I'm using ESP8266 ESP07 and I can't seem do be able to publish on my feed. I am able to receive data from the feed. On the serial port it say's it was successfully publish, but nothing appears on the IO page:

Sending photocell val 300...OK!

Sending photocell val 301...OK!

Sending photocell val 302...OK!

Sending photocell val 303...OK!

At the IO page the following error is displayed:

2015-12-22 19:34:43 - ERROR - feed photocell: undefined method `feeds' for nil:NilClass

What is the problem?

**Comment by andrealmeidadomingues** [comment]
I deleted my IO account and created another one. It works now. Finally. Thanks for everyone help.

**Comment by ladyada** [comment]
ok cool!
