### ISSUE TITLE
Don't send clear text over the Internet

### ISSUE THREAD

**Issue by probonopd** [adafruit/Adafruit_MQTT_Library#26]
Don't send clear text over the Internet, please consider using `WiFiClientSecure client;` on ESP8266 as mentioned [here](https://github.com/esp8266/Arduino/issues/43#issuecomment-154773929).

**Comment by ladyada** [comment]
have you used it successfully and for long terms?

**Comment by probonopd** [comment]
Haven't had a chance to try that for "long term" connections so far but people have used it for https.

**Comment by ladyada** [comment]
ok it seems to work for adafruit.io, added to examples!

**Comment by probonopd** [comment]
Wow, that was quick, thanks @ladyada
