### ISSUE TITLE
Adafruit_SleepyDog.h No such file or directory

### ISSUE THREAD

**Issue by squirrelsRduck** [adafruit/Adafruit_MQTT_Library#27]
Tried running this via the compiler from arduino.org on a macintosh El Capitan, and get this error for the mqtt_cc3k example.  Note, the chip works perfectly using the buildtest from the CC3000 breakout board's library:

cc3000helper.cpp:1:32: fatal error: Adafruit_SleepyDog.h: No such file or directory
 #include <Adafruit_SleepyDog.h>
                                ^
compilation terminated.
Error compiling.

**Comment by ladyada** [comment]
The library is here
https://github.com/adafruit/Adafruit_SleepyDog

**Comment by OMGdaDPS** [comment]
thank you for this Mrs. Ada!
