### ISSUE TITLE
Callback and subscription to sub-topics

### ISSUE THREAD

**Issue by noelgeorgi** [adafruit/Adafruit_MQTT_Library#32]
I switched to Adafruit MQTT from pubsubclient only for the purpose of SSL with esp8266, but I  am unable to subscribe to subtopics using **topic/+/+** as it was possible in PubSubClient and the callback function is a much needed feature...  even though the library contains
```
void Adafruit_MQTT_Subscribe::setCallback(SubscribeCallbackType cb) {
  callback = cb;
}

void Adafruit_MQTT_Subscribe::removeCallback(void) {
  callback = 0;
```
**using mqtt.setCallback** results in error:
** mqtt.setCallback();
          ^
exit status 1
'class Adafruit_MQTT_Client' has no member named 'setCallback'**

**Comment by ladyada** [comment]
thats right, it is not finished yet

**Comment by noelgeorgi** [comment]
Meanwhile i will try different libraries and stick with the one supporting ssl smoothly over the long run, PubSubClient works with ssl but frequent disconnections and ssl handshake error..

**Comment by ladyada** [comment]
callbacks are done - check the example! :)
