### ISSUE TITLE
MQTT library to node-red instead of adafruit i/o

### ISSUE THREAD

**Issue by TinajaLabs** [adafruit/Adafruit_MQTT_Library#37]
Can anyone provide suggestions about how one could use the esp8266 examples but instead use a local node-red mqtt/mosquitto broker instead of adafruit io.  My setup needs to be stand-alone.  

Could it be as simple as pointing to the ```local node-red address``` instead of ```io.adafruit.com``` in the ```AIO_SERVER``` definition?

Thanks for any advice,
Chris.

**Comment by fariz** [comment]
Yah i am in same problem with TinajLabs, we built standalone broker using mosquitto, help please how can my nodemcu can subscribe

**Comment by stelgenhof** [comment]
Yes, you can just point to your own MQTT broker adjusting these definitions. I adjusted it just like this:

```
#define AIO_SERVER      "<YOUR_MQTT_IP>"
#define AIO_SERVERPORT  <YOUR_MQTT_PORT>
```
Since my MQTT broker doesn't require username/password, I left the AIO_USERNAME, AIO_KEY as is. This worked perfectly fine!

**Comment by jwcooper** [comment]
Thank you for providing an answer @stelgenhof. Please continue any further discussion at the forums at https://forums.adafruit.com. Thanks!

**Comment by TinajaLabs** [comment]
Thanks...  I'll give it a try.  I used another lib, from http://pubsubclient.knolleary.net/, and it seems to be working well.
