### ISSUE TITLE
Sending Float/Double values result in empty payload

### ISSUE THREAD

**Issue by stelgenhof** [adafruit/Adafruit_MQTT_Library#38]
When trying to send a float/double value (for example temperature), the payload on the subscriber is empty. Even though the library supports float/double values, it doesn't seem to work. Sending strings/chars work fine on the other hand.

**Comment by ductsoup** [comment]
I have the same experience with a Feather M0. Here's the problem I think.

[https://learn.adafruit.com/adafruit-feather-m0-basic-proto/adapting-sketches-to-m0](url)

**Adafruit_MQTT.cpp**
`#if defined(ARDUINO_SAMD_ZERO) || defined(ARDUINO_SAMD_MKR1000)
static char *dtostrf (double val, signed char width, unsigned char prec, char *sout) {
  char fmt[20];
  sprintf(fmt, "%%%d.%df", width, prec);
  sprintf(sout, fmt, val);
  return sout;
}
#endif`

**Comment by stelgenhof** [comment]
Thanks! I remember creating a similar workaround but didn't work. Let me try yours :) Anyway would be nice if it could be incorporated in the main source

**Comment by ladyada** [comment]
this is good now...i tested it and it works on m0+winc1500
plz reopen if not
