### ISSUE TITLE
Issues with Multiple Subscriptions

### ISSUE THREAD

**Issue by IAmOrion** [adafruit/Adafruit_MQTT_Library#39]
Please see my Adafruit forum post for more: 
https://forums.adafruit.com/viewtopic.php?f=56&t=96262&p=483586

 I have 2 toggle switches in my dashboard.  The first switch works as expected, but the second seems to send the ON or OFF message TWICE with a split second time between.

The Arduino MQTT Library reads ON and OFF correctly as the first subscribed topic, however, the second subscription is getting ON1 or OFF1 from the second toggle switch subscription.  If I test in MQTT.fx the second toggle does indeed send the same message twice.

For example, I toggle ON, and ON is sent once at: 14-05-2016__03/53/25.14005532
                                then again almost instantly at: 14-05-2016__03/53/25.14005533

In the arduino serial monitor, not only does it add the 1 to the OFF / ON being sent, but it also adds blank characters.  (I finally discovered this by serial printing the char count of the received message) so for example, OFF1 was reporting 5 characters and not the expected 4.  That's when I realised that there is the ESCAPE character ( \x1B ) being sent after ON1, and \x1C being sent after OFF1.

That finally explains why my 0 == strcmp was failing even when I had what I though was being returned - strcmp(OFF1,OFF1).

**Comment by wifixcort** [comment]
We saw the same problem with ON1/OFF1 in an ESP8266 and our solution was update our mqtt library.

**Comment by ladyada** [comment]
oh yeah, i fixed this, it was due to not parsing packet length right before
