### ISSUE TITLE
Issue with Feather Huzza 

### ISSUE THREAD

**Issue by asafmatan** [adafruit/Adafruit_MQTT_Library#43]
Hi and thanks for this great lib

Regarding Adafruit_MQTT::readSubscription,  and IDE 1.6.9
I'm using feather huzza. and CloudMQTT to send GPS data 

IDE ver Adafruit_MQTT::readSubscription

I have notice that I get response from this function only in rare cases:

I dig down with DEBUD_MTQQ and notices that topiclen offset is sometimes different from 3.

sometimes the vlaue is 4 somethimes smaller than 3. have you noticed this issue? when this happen ofcourse the function cannot parse further.

I checked the data from the server using websocket UI and its all correct.

BTW I had to enlarge SUBSCRIPTIONDATALEN and MAXBUFFERSIZE  as the messge that comes from CloudMQTT somethimes is >125B length.

**Comment by ladyada** [comment]
im pretty sure this is fixed in recent pushes, you can send huge packets now
