### ISSUE TITLE
Issue working with Interrupts. Reseting

### ISSUE THREAD

**Issue by taralshah123** [adafruit/Adafruit_MQTT_Library#45]
Exception (9):
epc1=0x40104fd0 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000003 depc=0x00000000

ctx: sys 
sp: 3ffffbf0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffd90:  3fff061c 3fff0cc4 00100400 3fff0c94  
3ffffda0:  401051fc 019789c5 3ffeec48 00000000  
3ffffdb0:  3ffedd20 3ffeec48 3fff0d24 0000001f  
3ffffdc0:  00000000 017fb241 40201098 00001388  
3ffffdd0:  3ffeec48 00000000 00000001 0000000b  
3ffffde0:  00000000 0000000b 3fff0c6c 402026b6  
3ffffdf0:  3ffeeb3c 0000000b 00000000 402026e0  
3ffffe00:  3ffe83b8 3ffefe9c 3ffe9478 4020397d  
3ffffe10:  3ffeeb5e 3ffed6d0 3ffffed0 00000001  
3ffffe20:  00000000 3ffeeb5e 3ffeeb3c 40202d1c  
3ffffe30:  e0033025 3ffeeb3c 00000000 40202d9c  
3ffffe40:  4022f888 3ffe83b8 4020fc0d 3ffffed0  
3ffffe50:  0034694d 0000000e 00000000 40202f0a  
3ffffe60:  7fffffff 3ffe93a0 3ffe93a0 40201c0f  
3ffffe70:  40106988 0000002c 00000008 401069d6  
3ffffe80:  ffffffff 00000020 3ffefeb4 00000000  
3ffffe90:  00000000 00000000 0000001f 00000022  
3ffffea0:  3fffc200 40106950 3fffc258 4000050c  
3ffffeb0:  40000f68 00000030 00000011 ffffffff  
3ffffec0:  40000f58 00000000 00000020 00000000  
3ffffed0:  00000007 40201010 3ffe8954 00000003  
3ffffee0:  00000009 3ffed584 3ffe8954 3fffdab0  
3ffffef0:  00000000 3fffdcb0 3ffedd40 00000030  
3fffff00:  00000000 00000000 3ffe9446 3ffe9490  
3fffff10:  401051fc 0180268f 3ffe8954 00000000  
3fffff20:  3ffedd20 3ffe8954 00000036 00000000  
3fffff30:  00000000 017fac7d 40204dcf 3ffe8954  
3fffff40:  3ffedd20 04cc24ba 60000600 00000001  
3fffff50:  40204e38 3ffe8954 3ffedd20 04cc24ba  
3fffff60:  40104f6e 017fb6aa 40205853 40201018  
3fffff70:  40219c68 3ffeec48 3ffedd20 04cc24ba  
3fffff80:  40219c8e 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffedd40 3fffdad0 3ffeed30 402034ff  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x0f
csum 0x0f
~ld

So what should i do to use interrupts?
I was integrating this interrupt code with your MQTT ESP8266 example and code was  like this:

/***************************************************
  Adafruit MQTT Library ESP8266 Example

  Must use ESP8266 Arduino from:
    https://github.com/esp8266/Arduino

  Works great with Adafruit's Huzzah ESP board & Feather
  ----> https://www.adafruit.com/product/2471
  ----> https://www.adafruit.com/products/2821

  Adafruit invests time and resources providing this open source code,
  please support Adafruit and open-source hardware by purchasing
  products from Adafruit!

  Written by Tony DiCola for Adafruit Industries.
  MIT license, all text above must be included in any redistribution
 ****************************************************/
#include <ESP8266WiFi.h>
#include "Adafruit_MQTT.h"
#include "Adafruit_MQTT_Client.h"

/************************* WiFi Access Point *********************************/

#define WLAN_SSID       "ssid"
#define WLAN_PASS       "psk"

/************************* Adafruit.io Setup *********************************/

#define AIO_SERVER      "192.168.43.14"
#define AIO_SERVERPORT  1883                   // use 8883 for SSL
#define AIO_USERNAME    ""
#define AIO_KEY         ""

/************ Global State (you don't need to change this!) ******************/

// Create an ESP8266 WiFiClient class to connect to the MQTT server.
WiFiClient client;
// or... use WiFiFlientSecure for SSL
//WiFiClientSecure client;

// Store the MQTT server, username, and password in flash memory.
// This is required for using the Adafruit MQTT library.
const char MQTT_SERVER[] PROGMEM    = AIO_SERVER;
const char MQTT_USERNAME[] PROGMEM  = AIO_USERNAME;
const char MQTT_PASSWORD[] PROGMEM  = AIO_KEY;

// Setup the MQTT client class by passing in the WiFi client and MQTT server and login details.
Adafruit_MQTT_Client mqtt(&client, MQTT_SERVER, AIO_SERVERPORT, MQTT_USERNAME, MQTT_PASSWORD);

/****************************** Feeds ***************************************/

// Setup a feed called 'photocell' for publishing.
// Notice MQTT paths for AIO follow the form: <username>/feeds/<feedname>
const char PHOTOCELL_FEED[] PROGMEM = AIO_USERNAME "test";
Adafruit_MQTT_Publish photocell = Adafruit_MQTT_Publish(&mqtt, PHOTOCELL_FEED);

// Setup a feed called 'onoff' for subscribing to changes.
const char ONOFF_FEED[] PROGMEM = AIO_USERNAME "onoff";
Adafruit_MQTT_Subscribe onoffbutton = Adafruit_MQTT_Subscribe(&mqtt, ONOFF_FEED);

/*************************** Sketch Code ************************************/

// Bug workaround for Arduino 1.6.6, it seems to need a function declaration
// for some reason (only affects ESP8266, likely an arduino-builder bug).
void MQTT_connect();

void Reset()
{
    photocell.publish("hii");
}

void setup() {
  Serial.begin(115200);
  delay(10);

  Serial.println(F("Adafruit MQTT demo"));

  // Connect to WiFi access point.
  Serial.println(); Serial.println();
  Serial.print("Connecting to ");
  Serial.println(WLAN_SSID);

  WiFi.begin(WLAN_SSID, WLAN_PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();

  Serial.println("WiFi connected");
  Serial.println("IP address: "); Serial.println(WiFi.localIP());

  // Setup MQTT subscription for onoff feed.
  mqtt.subscribe(&onoffbutton);
  pinMode(D5, INPUT_PULLUP);
  attachInterrupt(D5, Reset, FALLING);

}

uint32_t x=0;

void loop() {
  // Ensure the connection to the MQTT server is alive (this will make the first
  // connection and automatically reconnect when disconnected).  See the MQTT_connect
  // function definition further below.
  MQTT_connect();

  // this is our 'wait for incoming subscription packets' busy subloop
  // try to spend your time here

  Adafruit_MQTT_Subscribe *subscription;
  while ((subscription = mqtt.readSubscription(5000))) {
    if (subscription == &onoffbutton) {
      Serial.print(F("Got: "));
      Serial.println((char *)onoffbutton.lastread);
    }
  }

  // Now we can publish stuff!
  Serial.print(F("\nSending photocell val "));
  Serial.print(x);
  Serial.print("...");
//  if (! photocell.publish(x++)) {
//    Serial.println(F("Failed"));
//  } else {
//    Serial.println(F("OK!"));
//  }

  // ping the server to keep the mqtt connection alive
  // NOT required if you are publishing once every KEEPALIVE seconds
  /*
  if(! mqtt.ping()) {
    mqtt.disconnect();
  }
  */
}

// Function to connect and reconnect as necessary to the MQTT server.
// Should be called in the loop function and it will take care if connecting.
void MQTT_connect() {
  int8_t ret;

  // Stop if already connected.
  if (mqtt.connected()) {
    return;
  }

  Serial.print("Connecting to MQTT... ");

  uint8_t retries = 3;
  while ((ret = mqtt.connect()) != 0) { // connect will return 0 for connected
       Serial.println(mqtt.connectErrorString(ret));
       Serial.println("Retrying MQTT connection in 5 seconds...");
       mqtt.disconnect();
       delay(5000);  // wait 5 seconds
       retries--;
       if (retries == 0) {
         // basically die and wait for WDT to reset me
         while (1);
       }
  }
  Serial.println("MQTT Connected!");
}

- Arduino board:  **NodeMCU**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.6.9**

**Comment by ladyada** [comment]
this is a tech support question more than a library issue. please contact NodeMCU seller for help on writing ESP8266 code. thank you!
