### ISSUE TITLE
The Adafruit_MQTT_Publish::publish(int32_t) transmits integers larger than 32768 incorrectly 

### ISSUE THREAD

**Issue by nelisse** [adafruit/Adafruit_MQTT_Library#49]
The Adafruit_MQTT_Publish::publish(int32_t) transmits integers larger than 32768 incorrectly 

**Solution**: Change itoa to ltoa since int32_t requires long type conversion

```
bool Adafruit_MQTT_Publish::publish(int32_t i) {
  char payload[18];
  ltoa(i, payload, 10); 
  return mqtt->publish(topic, payload, qos);
}
```

**Comment by ladyada** [comment]
what platform is this on? could not reproduce on ESP8266 :)

**Comment by ladyada** [comment]
(fixed but still unclear)

**Comment by nelisse** [comment]
Arduino Uno, Mega and Yun
I guess it is à 16/32 bits issue then

**Comment by nelisse** [comment]
Hi,
 
In short: since ATmega typically is 16 bits for integers and ARM is 32 bits,
int <> int32_t and unsigned int <> unit32_t for different Arduino platforms
For an int32_t or uint32_t parameter one has to use the ltoa or ultoa
variants to get it working correctly on all 16/32 bits platforms.
See below my Arduino example code and the output on a Uno/Mega/Yun (16 bits
integers), and Zero/HUZZAH ESP8266 (32 bit integers)
Hope this explains why ;-)
 
Martin
 
 
#include <limits.h>
 
void setup()
{
  char          payload[18];

  int           integer = 32767; // INT_MAX
  unsigned int  unsigned_integer = 65535; // UINT_MAX
  int32_t       signed_integer_32 = 2147483647; // INT32_MAX = LONG_MAX
  uint32_t      unsigned_integer_32 = 4294967295; // UINT32_MAX = ULONG_MAX
 
  Serial.begin(115200); // Serial.begin(9600);
  
  Serial.println(F("\nRange of data types\n")); //
<https://www.arduino.cc/en/Reference/Int>
https://www.arduino.cc/en/Reference/Int
 
  Serial.print(F("INT: "));
  Serial.print(INT_MIN);  
  Serial.print(F(" "));
  Serial.println(INT_MAX);  
  
  Serial.print(F("UINT: "));
  Serial.print(0);  
  Serial.print(F(" "));
  Serial.println(UINT_MAX);  
 
  Serial.print(F("LONG: "));
  Serial.print(LONG_MIN);  
  Serial.print(F(" "));
  Serial.println(LONG_MAX);  
  
  Serial.print(F("ULONG: "));
  Serial.print(0);  
  Serial.print(F(" "));
  Serial.println(ULONG_MAX);
  
  Serial.println(F("\nUsage of itoa variants"));
  
  Serial.println(F("\nint: 32767"));  
  Serial.print(F("  itoa: "));  itoa(integer, payload, 10);
Serial.println(payload);
  Serial.print(F("  ltoa: "));  ltoa(integer, payload, 10);
Serial.println(payload);
  Serial.print(F("  ultoa: ")); ultoa(integer, payload, 10);
Serial.println(payload);
  
  Serial.println(F("\nunsigned int: 65535")); 
  Serial.print(F("  itoa: "));  itoa(unsigned_integer, payload, 10);
Serial.println(payload);
  Serial.print(F("  ltoa: "));  ltoa(unsigned_integer, payload, 10);
Serial.println(payload);
  Serial.print(F("  ultoa: ")); ultoa(unsigned_integer, payload, 10);
Serial.println(payload);
  
  Serial.println(F("\nint32_t: 2147483647")); 
  Serial.print(F("  itoa: "));  itoa(signed_integer_32, payload, 10);
Serial.println(payload);
  Serial.print(F("  ltoa: "));  ltoa(signed_integer_32, payload, 10);
Serial.println(payload);
  Serial.print(F("  ultoa: ")); ultoa(signed_integer_32, payload, 10);
Serial.println(payload);
  
  Serial.println(F("\nuint32_t: 4294967295")); 
  Serial.print(F("  itoa: "));  itoa(unsigned_integer_32, payload, 10);
Serial.println(payload);
  Serial.print(F("  ltoa: "));  ltoa(unsigned_integer_32, payload, 10);
Serial.println(payload);
  Serial.print(F("  ultoa: ")); ultoa(unsigned_integer_32, payload, 10);
Serial.println(payload);  
}
 
void loop()
{
}  

 
------------------------------------------
Arduino Uno/Mega/Yun
 
Range of data types
 
INT: -32768 32767
UINT: 0 65535
LONG: -2147483648 2147483647
ULONG: 0 4294967295
 
Usage of itoa variants
 
int: 32767
  itoa: 32767
  ltoa: 32767
  ultoa: 32767
 
unsigned int: 65535
  itoa: -1
  ltoa: 65535
  ultoa: 65535
 
int32_t: 2147483647
  itoa: -1
  ltoa: 2147483647
  ultoa: 2147483647
 
uint32_t: 4294967295
  itoa: -1
  ltoa: -1
  ultoa: 4294967295

-----------------------------------------
Arduino Zero/M0, Adafruit HUZZAH ESP8266

Range of data types
 
INT: -2147483648 2147483647
UINT: 0 4294967295
LONG: -2147483648 2147483647
ULONG: 0 4294967295
 
Usage of itoa variants
 
int: 32767
  itoa: 32767
  ltoa: 32767
  ultoa: 32767
 
unsigned int: 65535
  itoa: 65535
  ltoa: 65535
  ultoa: 65535
 
int32_t: 2147483647
  itoa: 2147483647
  ltoa: 2147483647
  ultoa: 2147483647
 
uint32_t: 4294967295
  itoa: -1
  ltoa: -1
  ultoa: 4294967295

  _____

**Comment by ladyada** [comment]
sigh libc :/
