### ISSUE TITLE
i want to connect by host name rather than the ip address of my raspberry pi. So how can i do that?

### ISSUE THREAD

**Issue by taralshah123** [adafruit/Adafruit_MQTT_Library#52]
I am connecting esp8266 with my raspberry pi. i am able to connect by ip address. 
in my pc using mosquitto i can connect with ip address or hostname as raspberry.local.

**Comment by stelgenhof** [comment]
The Adafruit_MQTT_Client accepts both IP addresses as hostnames. You should be able to connect either way.

**Comment by taralshah123** [comment]
I mean i already tried by hostname. I am able to connect throuh hostnames such as adafruit.io server. But for my devices over local network i am not able to do this.

**Comment by stelgenhof** [comment]
Could you share some more details? For example do you get any error message from the node? How is your node connected to your network? Looks like DNS related.

**Comment by ladyada** [comment]
assuming resolved
