### ISSUE TITLE
Configurable SUBSCRIPTIONDATALEN

### ISSUE THREAD

**Issue by sgrimee** [adafruit/Adafruit_MQTT_Library#59]
Setting in the library:
```
#define SUBSCRIPTIONDATALEN 20
```
means the data length cannot be increased without having to modify the Adafruit_MQTT.h file.

Would it be possible to make that configurable, either by passing the value in the constructor or preventing redefinition of SUBSCRIPTIONDATALEN if it is already defined?

**Comment by ladyada** [comment]
no, because we're not using malloc()
