### ISSUE TITLE
io.adafruit.com SSL Certificate Expiry

### ISSUE THREAD

**Issue by trananhtuan** [adafruit/Adafruit_MQTT_Library#60]
Please consider using a **self-signed cert for MQTTS**. The current third-party io.adafruit.com cert is going to expire on July 2017.
Due to limitations, cert fingerprint needs to be hard-coded in the microcontroller (for cert verification to work) and therefore it needs update everytime io.adafruit.com cert is re-issued . This is unreasonable for IoT devices.

**Comment by ladyada** [comment]
this is more of an issue for io.adafruit (cert expiry length) not the MQTT library, right?

**Comment by trananhtuan** [comment]
I'm not sure where else should I turn to, could you point me to the right place? I think this is a legitimate issue and it deserves attention.

**Comment by ladyada** [comment]
https://github.com/adafruit/io-issues !

**Comment by trananhtuan** [comment]
I'm not sure where else should I turn to, could you point me to the right
place? I think this is a legitimate issue and it deserves attention.
