### ISSUE TITLE
connecting to mqtt failed (after requesting DHCP failed)

### ISSUE THREAD

**Issue by DorBenisti** [adafruit/Adafruit_MQTT_Library#69]
Hi, 

I have a big problem with cc3000 wifi shield.
I succeed connect to wifi network but when I am trying connect to mqtt by the library - it failed.

![mqtt error](https://cloud.githubusercontent.com/assets/25307151/22622548/aa11f530-eb45-11e6-8e39-02adac259300.png)

before the connection failed I have problem with the IP address (request DHCP) as you can see it here.
If I run web client of adafruit cc3000, I can connect to wifi and do GET http and all is good.

please tell me what is wrong and what I can do.

Thanks.

**Comment by ladyada** [comment]
hiya - we dont support CC3000 anymore. we recommend WiFi101 shield for MQTT
