### ISSUE TITLE
Support connecting to AWS IoT with Fona

### ISSUE THREAD

**Issue by andrei-ivanov** [adafruit/Adafruit_MQTT_Library#70]
I bought 2 Feathers M0 RFM69 and a Fona 808 breakout to send data to the AWS IoT, just to [discover](https://forums.adafruit.com/viewtopic.php?f=31&t=91242) that it can't actually connect to AWS :-(
Before buying I've seen that it has MQTT support, but I didn't think there was anything special required for AWS.
Not sure what to do now, if there's any chance for this to happen or if I should just return the Fona and look for another solution.

**Comment by ladyada** [comment]
there's little chance for the Fona to work with AWS due to AWS's severe authentication requirements.

**Comment by andrei-ivanov** [comment]
Can you please at least put a warning on the product page regarding this limitation?
I'll proceed with returning the board.
