### ISSUE TITLE
Can't keep connection open with 2+ MQTT devices

### ISSUE THREAD

**Issue by marcoschwartz** [adafruit/Adafruit_MQTT_Library#8]
Hello,

I've been working on several guides for Adafruit using Adafruit IO with this MQTT library.

This morning I was working on my latest guide, and I found something strange.

I first configured a device based on an Arduino Uno + CC3000 chip, which will simply publish data to a feed when a sensor reads some given value. This works just fine.

Then, I configured another device, based on the ESP8266, that just subscribes to another feed, and will act on a relay depending on this feed.

Both devices works fine on their own, but I had problems when I put them both together: I can't get the whole project working. I confirmed that by plugging the Arduino first, watching the Serial monitor, and then powering the ESP8266: both just can't keep the MQTT connection open with Adafruit IO. 

Is that something you already encountered before, or am I doing something wrong? Thanks!

**Comment by ladyada** [comment]
oh yah this is because MQTT_CLIENTID[] has to be unique - replace
const char MQTT_CLIENTID[] PROGMEM  = AIO_KEY __DATE__ __TIME__;
with
const char MQTT_CLIENTID[] PROGMEM  = "marcoesp8266";
and
const char MQTT_CLIENTID[] PROGMEM  = "marcocc3000;
just make sure each client has a unique id!

**Comment by marcoschwartz** [comment]
I knew I made a mistake somewhere - thanks for the tip, it definitely works now :) Closing the issue.
