### ISSUE TITLE
Connection to different MQTT Broker

### ISSUE THREAD

**Issue by architmuchhal12** [adafruit/Adafruit_MQTT_Library#85]
I am using an Espressif ESP32 on Arduino IDE to connect to an MQTT server using Adafruit FONA808. I was able to work along with the IoT platform run by Adafruit ([io.adafruit.com](URL)).

Now, I want to use the same system to connect to a different MQTT broker other than Adafruit IO. Is it possible to connect or the **Adafruit MQTT library** is tailor-made for just to establish a connection to Adafruit IO?

Thanks

**Comment by ladyada** [comment]
its generic MQTT so should work!
