### ISSUE TITLE
Update fingerprint declaration in "adafruitio_esp8266_sicure" sketch

### ISSUE THREAD

**Issue by biagiom** [adafruit/Adafruit_MQTT_Library#86]
https://github.com/adafruit/Adafruit_MQTT_Library/blob/1e3fb01778ef9eddcf68b5ac5f8a1cd6ec923a81/examples/adafruitio_secure_esp8266/adafruitio_secure_esp8266.ino#L44

Since the SSL fingerprint of AdafruitIO has been changed as shown in the [86733a8 commit of Adafruit_IO_Arduino repo](https://github.com/adafruit/Adafruit_IO_Arduino/commit/86733a8a6c0107d897d7fc4c37197f24e9e3e10d) the adafruitio_esp8266_sicure sketch should be updated:
`const char *fingerprint = "AD 4B 64 B3 67 40 B5 FC 0E 51 9B BD 25 E9 7F 88 B6 2A A3 5B";`

Best regards,
Biagio

**Comment by jwcooper** [comment]
Thanks for the bug report. This change has been made to master.
